use_frameworks!

platform :ios, '14.0'

target 'AardvarkCrashReportDemo' do
  pod 'AardvarkCrashReport', :path => '../AardvarkCrashReport.podspec'

  pod 'Aardvark', '~> 5.0'
  pod 'AardvarkLoggingUI', '~> 2.0'
  pod 'AardvarkMailUI', '~> 2.0'
  pod 'Paralayout', :git => 'https://github.com/square/Paralayout.git', :tag => '1.0.0-rc.5'
  pod 'PLCrashReporter', '~> 1.10'
end
