name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  xcode-build:
    name: Xcode Build
    runs-on: macOS-10.15
    strategy:
      matrix:
        platform: ['iOS_14', 'iOS_13']
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install --gemfile=Example/Gemfile
      - name: Select Xcode Version (12.2)
        run: sudo xcode-select --switch /Applications/Xcode_12.2.app/Contents/Developer
        if: matrix.platform == 'iOS_14'
      - name: Prepare iOS 13 Simulator
        run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s /Applications/Xcode_11.7.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 13.7.simruntime
          xcrun simctl list runtimes
          xcrun simctl create custom-test-device "iPhone 11 Pro" "com.apple.CoreSimulator.SimRuntime.iOS-13-3"
          xcrun simctl list devices 13.3
        if: matrix.platform == 'iOS_13'
      - name: Pod Install
        run: bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
      - name: Build and Test
        run: Scripts/build.swift xcode ${{ matrix.platform }} `which xcpretty`
  pod-lint:
    name: Pod Lint
    runs-on: macOS-10.15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install --gemfile=Example/Gemfile
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_12.2.app/Contents/Developer
      - name: Lint AardvarkCrashReport Podspec
        run: bundle exec --gemfile=Example/Gemfile pod lib lint --verbose --fail-fast AardvarkCrashReport.podspec --allow-warnings
