name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  xcode-build:
    name: Xcode Build
    runs-on: macOS-13
    strategy:
      matrix:
        platform: ['iOS_17', 'iOS_16']
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install --gemfile=Example/Gemfile
      - name: Prepare iOS 13 Simulator
        run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s /Applications/Xcode_14.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 16.4.simruntime
          xcrun simctl list runtimes
        if: matrix.platform == 'iOS_16'
      - name: Pod Install
        run: bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
      - name: Build and Test
        run: Scripts/build.swift xcode ${{ matrix.platform }} `which xcpretty`
  pod-lint:
    name: Pod Lint
    runs-on: macOS-13
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install --gemfile=Example/Gemfile
      - name: Lint AardvarkCrashReport Podspec
        run: bundle exec --gemfile=Example/Gemfile pod lib lint --verbose --fail-fast AardvarkCrashReport.podspec --allow-warnings
  swift-build:
    name: Swift Build
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Build
        run: |
          sudo xcode-select -s /Applications/Xcode_15.4.0.app
          xcodebuild build \
            -scheme AardvarkCrashReport \
            -sdk iphonesimulator17.5 \
            -destination "OS=17.5,name=iPhone 15 Pro"
